  nav:
    - index.md
    - basic-usage.md
    - Features:
      - features/named-handlers.md
      - features/verbosity.md
    - API Documentation:
      - splatlog:
        - lib:
          - text:
            - "fmt_type_hint Examples": splatlog/lib/text/fmt_type_hint.md

